# Generated by Django 4.0.6 on 2022-07-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('addr', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('webadr', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=200)),
                ('contact_info_desc', models.TextField()),
            ],
        ),
    ]
