# Generated by Django 4.0.6 on 2022-07-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('space', models.CharField(max_length=50)),
                ('support', models.CharField(max_length=50)),
            ],
        ),
    ]
