# Generated by Django 4.0.6 on 2022-08-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
